; SIDEY-specific strings. Standard wizard buttons/pages come from NSIS's NLF files.
LangString LanguageSelectionFailed ${LANG_ENGLISH} "The language selection window could not be opened.$\r$\n$\r$\nRun Setup again.$\r$\n$\r$\nError code: 0x51DE2009"
LangString LanguageSelectionFailed ${LANG_KOREAN} "언어 선택 창을 열지 못했습니다.$\r$\n$\r$\n설치 프로그램을 다시 실행하세요.$\r$\n$\r$\n오류 코드: 0x51DE2009"
LangString LanguageSelectionFailed ${LANG_JAPANESE} "言語選択画面を開けませんでした。$\r$\n$\r$\nセットアップを再実行してください。$\r$\n$\r$\nエラーコード: 0x51DE2009"
LangString LanguageSelectionFailed ${LANG_SIMPCHINESE} "无法打开语言选择窗口。$\r$\n$\r$\n请重新运行安装程序。$\r$\n$\r$\n错误代码：0x51DE2009"
LangString LanguageSelectionFailed ${LANG_TRADCHINESE} "無法開啟語言選擇視窗。$\r$\n$\r$\n請重新執行安裝程式。$\r$\n$\r$\n錯誤代碼：0x51DE2009"
LangString LanguageSelectionFailed ${LANG_RUSSIAN} "Не удалось открыть окно выбора языка.$\r$\n$\r$\nЗапустите программу установки ещё раз.$\r$\n$\r$\nКод ошибки: 0x51DE2009"
LangString LanguageSelectionFailed ${LANG_UKRAINIAN} "Не вдалося відкрити вікно вибору мови.$\r$\n$\r$\nЗапустіть програму встановлення ще раз.$\r$\n$\r$\nКод помилки: 0x51DE2009"

LangString LegacyRelocationBlocked ${LANG_JAPANESE} "以前の SIDEY の場所を安全に更新できず、Program Files の移行先も使用できません。セットアップは変更を加えていません。問題が続く場合は、診断データを GitHub Issue に添付してください。"
LangString LegacyRelocationNotice ${LANG_JAPANESE} "SIDEY を Program Files にインストールしましたが、下記の以前の場所にファイルが残っています。新しい SIDEY の起動を確認してから終了し、エクスプローラーで古い SIDEY のプログラムファイルを削除してください。関係のないファイルは残してください。以前のアンインストーラーは実行しないでください。設定とサインイン情報は別の場所に保存されています。"
LangString LegacyRelocationBlocked ${LANG_SIMPCHINESE} "无法安全更新 SIDEY 的原安装位置，Program Files 中的新位置也不可用。安装程序未作任何更改。如果问题持续，请在 GitHub 议题中附上诊断数据。"
LangString LegacyRelocationNotice ${LANG_SIMPCHINESE} "SIDEY 已安装到 Program Files，但无法清除以下原位置的全部文件。确认新版 SIDEY 能启动后，关闭应用并在文件资源管理器中删除旧版 SIDEY 程序文件。保留无关文件。不要运行旧版卸载程序。设置和登录数据另存于其他位置。"
LangString LegacyRelocationBlocked ${LANG_TRADCHINESE} "無法安全更新 SIDEY 的原安裝位置，Program Files 中的新位置也無法使用。安裝程式未進行任何變更。如果問題持續，請在 GitHub 議題附上診斷資料。"
LangString LegacyRelocationNotice ${LANG_TRADCHINESE} "SIDEY 已安裝至 Program Files，但無法清除以下原位置的所有檔案。確認新版 SIDEY 能啟動後，關閉程式並在檔案總管中刪除舊版 SIDEY 程式檔案。請保留無關檔案。不要執行舊版解除安裝程式。設定和登入資料另存於其他位置。"
LangString LegacyRelocationBlocked ${LANG_RUSSIAN} "Предыдущее расположение SIDEY нельзя безопасно обновить, а новое расположение в Program Files недоступно. Установщик ничего не изменил. Если проблема повторится, приложите диагностические данные к сообщению об ошибке на GitHub."
LangString LegacyRelocationNotice ${LANG_RUSSIAN} "SIDEY установлен в Program Files, но не все файлы в прежней папке ниже удалось удалить. Убедитесь, что новая версия запускается, закройте SIDEY и удалите старые файлы программы через Проводник. Не трогайте посторонние файлы и не запускайте старую программу удаления. Настройки и данные входа хранятся отдельно."
LangString LegacyRelocationBlocked ${LANG_UKRAINIAN} "Попереднє розташування SIDEY не можна безпечно оновити, а нове розташування в Program Files недоступне. Інсталятор нічого не змінив. Якщо проблема повториться, додайте діагностичні дані до повідомлення про помилку на GitHub."
LangString LegacyRelocationNotice ${LANG_UKRAINIAN} "SIDEY встановлено до Program Files, але не всі файли в попередній папці нижче вдалося видалити. Переконайтеся, що нова версія запускається, закрийте SIDEY та видаліть старі файли програми в Провіднику. Не чіпайте сторонні файли й не запускайте старий засіб видалення. Налаштування та дані входу зберігаються окремо."

LangString LaunchSidey ${LANG_JAPANESE} "SIDEY を起動する"
LangString TermsTitle ${LANG_JAPANESE} "SIDEY 利用規約"
LangString TermsSubtitle ${LANG_JAPANESE} "インストールする前に、利用規約を確認して同意してください。"
LangString TermsTop ${LANG_JAPANESE} "以下の利用規約をお読みください。続行するには同意のチェックボックスを選択してください。"
LangString AcceptTerms ${LANG_JAPANESE} "SIDEY の利用規約を読み、同意します。"
LangString MaintenanceTitle ${LANG_JAPANESE} "SIDEY は既にインストールされています"
LangString MaintenanceSubtitle ${LANG_JAPANESE} "実行する操作を選択してください。"
LangString MaintenanceDescription ${LANG_JAPANESE} "同じバージョンの SIDEY がインストールされています。修復またはアンインストールを選択できます。"
LangString RepairAction ${LANG_JAPANESE} "修復"
LangString RemoveAction ${LANG_JAPANESE} "アンインストール"
LangString CloseAction ${LANG_JAPANESE} "閉じる"
LangString DowngradeBlocked ${LANG_JAPANESE} "新しいバージョンの SIDEY が既にインストールされているため、変更は行われませんでした。${APP_VERSION} をインストールするには、Windows の設定 > アプリから現在の SIDEY をアンインストールし、このセットアップを再実行してください。"
LangString LegacyMigrationManual ${LANG_JAPANESE} "以前の SIDEY MSI がインストールされているため、変更は行われませんでした。Windows の設定 > アプリからアンインストールし、このセットアップを再実行してください。SIDEY のインストールファイルを手動で削除しないでください。"
LangString ExistingRemovalFailed ${LANG_JAPANESE} "既存の SIDEY を削除できません。必要なインストールファイルが見つからないか、使用中の可能性があります。$\r$\n$\r$\nこのセットアップを再実行して修復を完了し、もう一度実行してアンインストールを選んでください。修復に失敗した場合は Windows を再起動して再試行してください。$\r$\n$\r$\n問題が続く場合は、この画面のスクリーンショットと診断データを添えて GitHub Issue を作成してください。$\r$\nSIDEY のインストールファイルを手動で削除しないでください。"
LangString CleanupTitle ${LANG_JAPANESE} "SIDEY のユーザーデータの削除"
LangString CleanupSubtitle ${LANG_JAPANESE} "削除する現在のユーザーのデータを選択してください。"
LangString CleanupDescription ${LANG_JAPANESE} "SIDEY アプリをアンインストールします。以下のデータは、選択しない限り保持されます。"
LangString DeleteLocalData ${LANG_JAPANESE} "設定とログを削除する (%LOCALAPPDATA%\SIDEY)"
LangString DeleteCredentials ${LANG_JAPANESE} "保存された SIDEY のログイン情報を削除する"
LangString CleanupFailed ${LANG_JAPANESE} "SIDEY アプリは削除されましたが、選択したユーザーデータの一部を削除できませんでした。$\r$\n$\r$\n残っている項目は次のとおりです。SIDEY アプリの削除には影響しません。$\r$\n$CleanupFailureDetails$\r$\n$\r$\n問題が続く場合は、この画面のスクリーンショットと診断データを添えて GitHub Issue を作成してください。"
LangString CleanupLocalDataFailure ${LANG_JAPANESE} "- 設定とログ (%LOCALAPPDATA%\SIDEY)"
LangString CleanupCredentialsFailure ${LANG_JAPANESE} "- 保存された SIDEY のログイン情報"
LangString CleanupStartupFailure ${LANG_JAPANESE} "- SIDEY のスタートアップ項目"
LangString LaunchFailed ${LANG_JAPANESE} "SIDEY のインストールは完了しましたが、アプリを起動できませんでした。$\r$\n$\r$\nWindows を再起動し、スタートメニューから SIDEY を起動してください。$\r$\n$\r$\n問題が続く場合は、この画面のスクリーンショットと診断データを添えて GitHub Issue を作成してください。"
LangString TransactionFailed ${LANG_JAPANESE} "SIDEY のインストールを完了できませんでした。既にインストールされていた場合、以前のインストールは保持または復元されました。$\r$\n$\r$\nセットアップを再実行してください。"
LangString TransactionStateUnknown ${LANG_JAPANESE} "インストール中に問題が発生し、SIDEY の最終的なインストール状態を確認できませんでした。$\r$\n$\r$\nWindows を再起動し、最新の SIDEY セットアップを実行してください。修復が表示された場合は完了してください。$\r$\n$\r$\nSIDEY のインストールファイルを手動で削除しないでください。"
LangString TransactionRecoveryFailed ${LANG_JAPANESE} "中断された SIDEY のインストールを復旧できず、最終状態を確認できませんでした。$\r$\n$\r$\nWindows を再起動し、最新の SIDEY セットアップを再実行してください。$\r$\n$\r$\nSIDEY のインストールファイルを手動で削除しないでください。"
LangString UninstallPreflightFailed ${LANG_JAPANESE} "SIDEY の削除を開始できませんでした。アンインストールによる変更は行われていません。$\r$\n$\r$\nSIDEY を終了し、Windows を再起動してから再試行してください。"
LangString UninstallStateUnknown ${LANG_JAPANESE} "削除中に問題が発生し、SIDEY の最終的な削除状態を確認できませんでした。$\r$\n$\r$\nWindows を再起動し、最新の SIDEY セットアップで削除を再試行してください。$\r$\n$\r$\nSIDEY のインストールファイルを手動で削除しないでください。"
LangString SetupAlreadyRunning ${LANG_JAPANESE} "別の SIDEY セットアップまたはアンインストーラーが実行中です。$\r$\n$\r$\n終了してから再試行してください。$\r$\n$\r$\nSIDEY エラーコード: 0x51DE2007"
LangString SetupInitializationFailed ${LANG_JAPANESE} "SIDEY セットアップでインストールロックを初期化できませんでした。$\r$\n$\r$\nWindows を再起動し、セットアップを再実行してください。$\r$\n$\r$\nSIDEY エラーコード: 0x51DE2008"
LangString CleanupPending ${LANG_JAPANESE} "SIDEY はインストールされましたが、以前のバージョンのバックアップを削除できませんでした。$\r$\n$\r$\n操作は不要です。次回のセットアップでクリーンアップを再試行します。"
LangString PayloadStageFailed ${LANG_JAPANESE} "SIDEY アプリのファイルを準備できませんでした。既存のインストールは置き換えられていません。$\r$\n$\r$\nWindows のシステムドライブと SIDEY のインストール先ドライブの空き容量を増やし、セットアップを再実行してください。"
LangString ProcessStopFailed ${LANG_JAPANESE} "SIDEY のプロセスが実行中のため、アプリのファイルを更新できませんでした。既存のインストールは保持されています。$\r$\n$\r$\nSIDEY を終了してセットアップを再実行してください。表示されない場合は Windows を再起動して再試行してください。"
LangString PayloadActivationFailed ${LANG_JAPANESE} "準備した SIDEY アプリのファイルを適用できませんでした。以前のインストールは保持または復元されました。$\r$\n$\r$\nWindows を再起動し、セットアップを再実行してください。"
LangString RegistrationFailed ${LANG_JAPANESE} "SIDEY のショートカットまたは Windows 登録情報を更新できませんでした。以前のインストールは保持または復元されました。$\r$\n$\r$\nWindows を再起動し、セットアップを再実行してください。"

LangString LaunchSidey ${LANG_SIMPCHINESE} "启动 SIDEY"
LangString TermsTitle ${LANG_SIMPCHINESE} "SIDEY 使用条款"
LangString TermsSubtitle ${LANG_SIMPCHINESE} "安装 SIDEY 前，请阅读并同意使用条款。"
LangString TermsTop ${LANG_SIMPCHINESE} "请阅读以下条款。勾选同意复选框后才能继续。"
LangString AcceptTerms ${LANG_SIMPCHINESE} "我已阅读并同意 SIDEY 使用条款。"
LangString MaintenanceTitle ${LANG_SIMPCHINESE} "已安装 SIDEY"
LangString MaintenanceSubtitle ${LANG_SIMPCHINESE} "请选择要执行的操作。"
LangString MaintenanceDescription ${LANG_SIMPCHINESE} "已安装相同版本的 SIDEY。您可以修复安装或卸载 SIDEY。"
LangString RepairAction ${LANG_SIMPCHINESE} "修复"
LangString RemoveAction ${LANG_SIMPCHINESE} "卸载"
LangString CloseAction ${LANG_SIMPCHINESE} "关闭"
LangString DowngradeBlocked ${LANG_SIMPCHINESE} "已安装更新版本的 SIDEY，因此安装程序未进行任何更改。要安装 ${APP_VERSION}，请从 Windows 设置 > 应用中卸载当前 SIDEY，然后重新运行此安装程序。"
LangString LegacyMigrationManual ${LANG_SIMPCHINESE} "检测到旧版 SIDEY MSI，因此安装程序未进行任何更改。请从 Windows 设置 > 应用中卸载该版本，然后重新运行此安装程序。请勿手动删除 SIDEY 安装文件。"
LangString ExistingRemovalFailed ${LANG_SIMPCHINESE} "无法卸载现有 SIDEY。所需的安装文件可能丢失或正在使用。$\r$\n$\r$\n请重新运行此安装程序并完成修复，然后再次运行并选择卸载。如果修复失败，请重启 Windows 后重试。$\r$\n$\r$\n如果问题仍然存在，请附上此窗口的截图和诊断数据提交 GitHub Issue。$\r$\n请勿手动删除 SIDEY 安装文件。"
LangString CleanupTitle ${LANG_SIMPCHINESE} "选择要删除的 SIDEY 用户数据"
LangString CleanupSubtitle ${LANG_SIMPCHINESE} "请选择要删除的当前用户数据。"
LangString CleanupDescription ${LANG_SIMPCHINESE} "SIDEY 应用将被卸载。以下数据仅在勾选后才会删除。"
LangString DeleteLocalData ${LANG_SIMPCHINESE} "删除设置和日志 (%LOCALAPPDATA%\SIDEY)"
LangString DeleteCredentials ${LANG_SIMPCHINESE} "删除已保存的 SIDEY 登录凭据"
LangString CleanupFailed ${LANG_SIMPCHINESE} "SIDEY 应用已卸载，但无法删除部分选定的用户数据。$\r$\n$\r$\n剩余项目如下。它们不会影响 SIDEY 应用的卸载。$\r$\n$CleanupFailureDetails$\r$\n$\r$\n如果问题仍然存在，请附上此窗口的截图和诊断数据提交 GitHub Issue。"
LangString CleanupLocalDataFailure ${LANG_SIMPCHINESE} "- 设置和日志 (%LOCALAPPDATA%\SIDEY)"
LangString CleanupCredentialsFailure ${LANG_SIMPCHINESE} "- 已保存的 SIDEY 登录凭据"
LangString CleanupStartupFailure ${LANG_SIMPCHINESE} "- SIDEY 启动项"
LangString LaunchFailed ${LANG_SIMPCHINESE} "SIDEY 已安装，但无法启动应用。$\r$\n$\r$\n请重启 Windows，然后从开始菜单启动 SIDEY。$\r$\n$\r$\n如果问题仍然存在，请附上此窗口的截图和诊断数据提交 GitHub Issue。"
LangString TransactionFailed ${LANG_SIMPCHINESE} "SIDEY 安装未完成。如果之前已安装 SIDEY，则先前的安装已保留或恢复。$\r$\n$\r$\n请重新运行安装程序。"
LangString TransactionStateUnknown ${LANG_SIMPCHINESE} "安装过程中出现问题，无法确认 SIDEY 的最终安装状态。$\r$\n$\r$\n请重启 Windows，然后运行最新的 SIDEY 安装程序。如果提供修复选项，请完成修复。$\r$\n$\r$\n请勿手动删除 SIDEY 安装文件。"
LangString TransactionRecoveryFailed ${LANG_SIMPCHINESE} "无法恢复中断的 SIDEY 安装，也无法确认最终安装状态。$\r$\n$\r$\n请重启 Windows，然后再次运行最新的 SIDEY 安装程序。$\r$\n$\r$\n请勿手动删除 SIDEY 安装文件。"
LangString UninstallPreflightFailed ${LANG_SIMPCHINESE} "无法开始卸载 SIDEY。尚未进行任何卸载更改。$\r$\n$\r$\n请关闭 SIDEY，重启 Windows 后重试。"
LangString UninstallStateUnknown ${LANG_SIMPCHINESE} "卸载过程中出现问题，无法确认 SIDEY 的最终卸载状态。$\r$\n$\r$\n请重启 Windows，然后使用最新的 SIDEY 安装程序重试卸载。$\r$\n$\r$\n请勿手动删除 SIDEY 安装文件。"
LangString SetupAlreadyRunning ${LANG_SIMPCHINESE} "另一个 SIDEY 安装程序或卸载程序正在运行。$\r$\n$\r$\n请先将其关闭后重试。$\r$\n$\r$\nSIDEY 错误代码：0x51DE2007"
LangString SetupInitializationFailed ${LANG_SIMPCHINESE} "SIDEY 安装程序无法初始化安装锁。$\r$\n$\r$\n请重启 Windows，然后再次运行安装程序。$\r$\n$\r$\nSIDEY 错误代码：0x51DE2008"
LangString CleanupPending ${LANG_SIMPCHINESE} "SIDEY 已安装，但无法删除旧版本备份。$\r$\n$\r$\n无需执行任何操作。下次运行安装程序时会重试清理。"
LangString PayloadStageFailed ${LANG_SIMPCHINESE} "无法准备 SIDEY 应用文件。现有安装未被替换。$\r$\n$\r$\n请释放 Windows 系统驱动器和 SIDEY 安装驱动器的空间，然后重新运行安装程序。"
LangString ProcessStopFailed ${LANG_SIMPCHINESE} "SIDEY 进程仍在运行，因此无法更新应用文件。现有安装已保留。$\r$\n$\r$\n请关闭 SIDEY 后重新运行安装程序。如果看不到 SIDEY，请重启 Windows 后重试。"
LangString PayloadActivationFailed ${LANG_SIMPCHINESE} "无法应用已准备的 SIDEY 应用文件。先前的安装已保留或恢复。$\r$\n$\r$\n请重启 Windows，然后重新运行安装程序。"
LangString RegistrationFailed ${LANG_SIMPCHINESE} "无法更新 SIDEY 快捷方式或 Windows 注册信息。先前的安装已保留或恢复。$\r$\n$\r$\n请重启 Windows，然后重新运行安装程序。"

LangString LaunchSidey ${LANG_TRADCHINESE} "啟動 SIDEY"
LangString TermsTitle ${LANG_TRADCHINESE} "SIDEY 使用條款"
LangString TermsSubtitle ${LANG_TRADCHINESE} "安裝 SIDEY 前，請閱讀並同意使用條款。"
LangString TermsTop ${LANG_TRADCHINESE} "請閱讀以下條款。勾選同意核取方塊後才能繼續。"
LangString AcceptTerms ${LANG_TRADCHINESE} "我已閱讀並同意 SIDEY 使用條款。"
LangString MaintenanceTitle ${LANG_TRADCHINESE} "已安裝 SIDEY"
LangString MaintenanceSubtitle ${LANG_TRADCHINESE} "請選擇要執行的操作。"
LangString MaintenanceDescription ${LANG_TRADCHINESE} "已安裝相同版本的 SIDEY。您可以修復安裝或解除安裝 SIDEY。"
LangString RepairAction ${LANG_TRADCHINESE} "修復"
LangString RemoveAction ${LANG_TRADCHINESE} "解除安裝"
LangString CloseAction ${LANG_TRADCHINESE} "關閉"
LangString DowngradeBlocked ${LANG_TRADCHINESE} "已安裝較新版本的 SIDEY，因此安裝程式未進行任何變更。若要安裝 ${APP_VERSION}，請從 Windows 設定 > 應用程式解除安裝目前的 SIDEY，然後重新執行此安裝程式。"
LangString LegacyMigrationManual ${LANG_TRADCHINESE} "偵測到舊版 SIDEY MSI，因此安裝程式未進行任何變更。請從 Windows 設定 > 應用程式解除安裝該版本，然後重新執行此安裝程式。請勿手動刪除 SIDEY 安裝檔案。"
LangString ExistingRemovalFailed ${LANG_TRADCHINESE} "無法解除安裝現有 SIDEY。必要的安裝檔案可能遺失或正在使用。$\r$\n$\r$\n請重新執行此安裝程式並完成修復，然後再次執行並選擇解除安裝。如果修復失敗，請重新啟動 Windows 後再試一次。$\r$\n$\r$\n如果問題持續，請附上此視窗的螢幕擷取畫面和診斷資料提交 GitHub Issue。$\r$\n請勿手動刪除 SIDEY 安裝檔案。"
LangString CleanupTitle ${LANG_TRADCHINESE} "選擇要刪除的 SIDEY 使用者資料"
LangString CleanupSubtitle ${LANG_TRADCHINESE} "請選擇要刪除的目前使用者資料。"
LangString CleanupDescription ${LANG_TRADCHINESE} "SIDEY 應用程式將被解除安裝。以下資料只有在勾選後才會刪除。"
LangString DeleteLocalData ${LANG_TRADCHINESE} "刪除設定和記錄 (%LOCALAPPDATA%\SIDEY)"
LangString DeleteCredentials ${LANG_TRADCHINESE} "刪除已儲存的 SIDEY 登入認證"
LangString CleanupFailed ${LANG_TRADCHINESE} "SIDEY 應用程式已移除，但無法刪除部分選取的使用者資料。$\r$\n$\r$\n剩餘項目如下。這不會影響 SIDEY 應用程式的移除。$\r$\n$CleanupFailureDetails"
LangString CleanupLocalDataFailure ${LANG_TRADCHINESE} "- 設定和記錄 (%LOCALAPPDATA%\SIDEY)"
LangString CleanupCredentialsFailure ${LANG_TRADCHINESE} "- 已儲存的 SIDEY 登入認證"
LangString CleanupStartupFailure ${LANG_TRADCHINESE} "- SIDEY 啟動項目"
LangString LaunchFailed ${LANG_TRADCHINESE} "SIDEY 已安裝，但無法啟動應用程式。$\r$\n$\r$\n請重新啟動 Windows，然後從開始功能表啟動 SIDEY。"
LangString TransactionFailed ${LANG_TRADCHINESE} "SIDEY 安裝未完成。如果先前已安裝 SIDEY，先前的安裝已保留或還原。$\r$\n$\r$\n請重新執行安裝程式。"
LangString TransactionStateUnknown ${LANG_TRADCHINESE} "安裝期間發生問題，無法確認 SIDEY 的最終安裝狀態。$\r$\n$\r$\n請重新啟動 Windows，然後執行最新的 SIDEY 安裝程式。若提供修復，請完成修復。$\r$\n$\r$\n請勿手動刪除 SIDEY 安裝檔案。"
LangString TransactionRecoveryFailed ${LANG_TRADCHINESE} "無法復原中斷的 SIDEY 安裝，也無法確認最終安裝狀態。$\r$\n$\r$\n請重新啟動 Windows，然後再次執行最新的 SIDEY 安裝程式。$\r$\n$\r$\n請勿手動刪除 SIDEY 安裝檔案。"
LangString UninstallPreflightFailed ${LANG_TRADCHINESE} "無法開始解除安裝 SIDEY。尚未進行任何解除安裝變更。$\r$\n$\r$\n請關閉 SIDEY，重新啟動 Windows 後再試一次。"
LangString UninstallStateUnknown ${LANG_TRADCHINESE} "解除安裝期間發生問題，無法確認 SIDEY 的最終解除安裝狀態。$\r$\n$\r$\n請重新啟動 Windows，然後使用最新的 SIDEY 安裝程式重試解除安裝。$\r$\n$\r$\n請勿手動刪除 SIDEY 安裝檔案。"
LangString SetupAlreadyRunning ${LANG_TRADCHINESE} "另一個 SIDEY 安裝程式或解除安裝程式正在執行。$\r$\n$\r$\n請先將其關閉後再試一次。$\r$\n$\r$\nSIDEY 錯誤代碼：0x51DE2007"
LangString SetupInitializationFailed ${LANG_TRADCHINESE} "SIDEY 安裝程式無法初始化安裝鎖定。$\r$\n$\r$\n請重新啟動 Windows，然後再次執行安裝程式。$\r$\n$\r$\nSIDEY 錯誤代碼：0x51DE2008"
LangString CleanupPending ${LANG_TRADCHINESE} "SIDEY 已安裝，但無法刪除舊版本備份。$\r$\n$\r$\n不需要任何操作。下次執行安裝程式時會重試清理。"
LangString PayloadStageFailed ${LANG_TRADCHINESE} "無法準備 SIDEY 應用程式檔案。現有安裝未被取代。$\r$\n$\r$\n請釋放 Windows 系統磁碟和 SIDEY 安裝磁碟的空間，然後重新執行安裝程式。"
LangString ProcessStopFailed ${LANG_TRADCHINESE} "SIDEY 處理程序仍在執行，因此無法更新應用程式檔案。現有安裝已保留。$\r$\n$\r$\n請關閉 SIDEY 後重新執行安裝程式。如果看不到 SIDEY，請重新啟動 Windows 後再試一次。"
LangString PayloadActivationFailed ${LANG_TRADCHINESE} "無法套用已準備的 SIDEY 應用程式檔案。先前的安裝已保留或還原。$\r$\n$\r$\n請重新啟動 Windows，然後重新執行安裝程式。"
LangString RegistrationFailed ${LANG_TRADCHINESE} "無法更新 SIDEY 捷徑或 Windows 登錄資訊。先前的安裝已保留或還原。$\r$\n$\r$\n請重新啟動 Windows，然後重新執行安裝程式。"

LangString LaunchSidey ${LANG_RUSSIAN} "Запустить SIDEY"
LangString TermsTitle ${LANG_RUSSIAN} "Условия использования SIDEY"
LangString TermsSubtitle ${LANG_RUSSIAN} "Перед установкой ознакомьтесь с условиями и примите их."
LangString TermsTop ${LANG_RUSSIAN} "Прочитайте условия ниже. Чтобы продолжить, установите флажок согласия."
LangString AcceptTerms ${LANG_RUSSIAN} "Я прочитал(а) и принимаю условия использования SIDEY."
LangString MaintenanceTitle ${LANG_RUSSIAN} "SIDEY уже установлен"
LangString MaintenanceSubtitle ${LANG_RUSSIAN} "Выберите нужное действие."
LangString MaintenanceDescription ${LANG_RUSSIAN} "Эта версия SIDEY уже установлена. Вы можете восстановить или удалить приложение."
LangString RepairAction ${LANG_RUSSIAN} "Восстановить"
LangString RemoveAction ${LANG_RUSSIAN} "Удалить"
LangString CloseAction ${LANG_RUSSIAN} "Закрыть"
LangString DowngradeBlocked ${LANG_RUSSIAN} "Уже установлена более новая версия SIDEY, поэтому установщик ничего не изменил. Чтобы установить ${APP_VERSION}, удалите текущую версию SIDEY в Параметры Windows > Приложения, затем снова запустите этот установщик."
LangString LegacyMigrationManual ${LANG_RUSSIAN} "Установлена предыдущая MSI-версия SIDEY, поэтому установщик ничего не изменил. Удалите её в Параметры Windows > Приложения, затем снова запустите этот установщик. Не удаляйте файлы установки SIDEY вручную."
LangString ExistingRemovalFailed ${LANG_RUSSIAN} "Не удалось удалить существующую установку SIDEY. Необходимые файлы могут отсутствовать или использоваться.$\r$\n$\r$\nСнова запустите эту программу установки и выполните восстановление, затем выберите удаление. Если восстановление завершится ошибкой, перезапустите Windows и повторите попытку.$\r$\n$\r$\nНе удаляйте файлы установки SIDEY вручную."
LangString CleanupTitle ${LANG_RUSSIAN} "Удаление пользовательских данных SIDEY"
LangString CleanupSubtitle ${LANG_RUSSIAN} "Выберите данные текущего пользователя для удаления."
LangString CleanupDescription ${LANG_RUSSIAN} "Приложение SIDEY будет удалено. Данные ниже сохранятся, если не отметить их для удаления."
LangString DeleteLocalData ${LANG_RUSSIAN} "Удалить настройки и журналы (%LOCALAPPDATA%\SIDEY)"
LangString DeleteCredentials ${LANG_RUSSIAN} "Удалить сохранённые учётные данные для входа в SIDEY"
LangString CleanupFailed ${LANG_RUSSIAN} "Приложение SIDEY удалено, но часть выбранных пользовательских данных удалить не удалось.$\r$\n$\r$\nОставшиеся элементы перечислены ниже. Они не влияют на удаление приложения SIDEY.$\r$\n$CleanupFailureDetails"
LangString CleanupLocalDataFailure ${LANG_RUSSIAN} "- Настройки и журналы (%LOCALAPPDATA%\SIDEY)"
LangString CleanupCredentialsFailure ${LANG_RUSSIAN} "- Сохранённые учётные данные для входа в SIDEY"
LangString CleanupStartupFailure ${LANG_RUSSIAN} "- Запись автозапуска SIDEY"
LangString LaunchFailed ${LANG_RUSSIAN} "SIDEY установлен, но приложение не удалось запустить.$\r$\n$\r$\nПерезапустите Windows и запустите SIDEY из меню «Пуск»."
LangString TransactionFailed ${LANG_RUSSIAN} "Установка SIDEY не завершена. Если SIDEY уже был установлен, предыдущая установка сохранена или восстановлена.$\r$\n$\r$\nСнова запустите программу установки."
LangString TransactionStateUnknown ${LANG_RUSSIAN} "Во время установки возникла проблема, и итоговое состояние SIDEY не удалось подтвердить.$\r$\n$\r$\nПерезапустите Windows и запустите последнюю версию установщика SIDEY. Если предлагается восстановление, завершите его.$\r$\n$\r$\nНе удаляйте файлы установки SIDEY вручную."
LangString TransactionRecoveryFailed ${LANG_RUSSIAN} "Не удалось восстановить прерванную установку SIDEY и подтвердить её итоговое состояние.$\r$\n$\r$\nПерезапустите Windows и снова запустите последнюю версию установщика SIDEY.$\r$\n$\r$\nНе удаляйте файлы установки SIDEY вручную."
LangString UninstallPreflightFailed ${LANG_RUSSIAN} "Не удалось начать удаление SIDEY. Изменения удаления не применялись.$\r$\n$\r$\nЗакройте SIDEY, перезапустите Windows и повторите попытку."
LangString UninstallStateUnknown ${LANG_RUSSIAN} "Во время удаления возникла проблема, и итоговое состояние удаления SIDEY не удалось подтвердить.$\r$\n$\r$\nПерезапустите Windows и повторите удаление с помощью последней версии установщика SIDEY.$\r$\n$\r$\nНе удаляйте файлы установки SIDEY вручную."
LangString SetupAlreadyRunning ${LANG_RUSSIAN} "Другая программа установки или удаления SIDEY уже запущена.$\r$\n$\r$\nЗакройте её и повторите попытку.$\r$\n$\r$\nКод ошибки SIDEY: 0x51DE2007"
LangString SetupInitializationFailed ${LANG_RUSSIAN} "Не удалось инициализировать блокировку установки SIDEY.$\r$\n$\r$\nПерезапустите Windows и снова запустите установщик.$\r$\n$\r$\nКод ошибки SIDEY: 0x51DE2008"
LangString CleanupPending ${LANG_RUSSIAN} "SIDEY установлен, но резервную копию предыдущей версии удалить не удалось.$\r$\n$\r$\nНикаких действий не требуется. Очистка будет повторена при следующем запуске установки."
LangString PayloadStageFailed ${LANG_RUSSIAN} "Не удалось подготовить файлы приложения SIDEY. Существующая установка не заменена.$\r$\n$\r$\nОсвободите место на системном диске Windows и диске установки SIDEY, затем снова запустите установщик."
LangString ProcessStopFailed ${LANG_RUSSIAN} "Не удалось обновить файлы приложения, так как процесс SIDEY всё ещё запущен. Существующая установка сохранена.$\r$\n$\r$\nЗакройте SIDEY и снова запустите установщик. Если SIDEY не виден, перезапустите Windows."
LangString PayloadActivationFailed ${LANG_RUSSIAN} "Не удалось применить подготовленные файлы приложения SIDEY. Предыдущая установка сохранена или восстановлена.$\r$\n$\r$\nПерезапустите Windows и снова запустите установщик."
LangString RegistrationFailed ${LANG_RUSSIAN} "Не удалось обновить ярлыки SIDEY или регистрацию в Windows. Предыдущая установка сохранена или восстановлена.$\r$\n$\r$\nПерезапустите Windows и снова запустите установщик."

LangString LaunchSidey ${LANG_UKRAINIAN} "Запустити SIDEY"
LangString TermsTitle ${LANG_UKRAINIAN} "Умови використання SIDEY"
LangString TermsSubtitle ${LANG_UKRAINIAN} "Перед встановленням ознайомтеся з умовами та прийміть їх."
LangString TermsTop ${LANG_UKRAINIAN} "Прочитайте умови нижче. Щоб продовжити, установіть прапорець згоди."
LangString AcceptTerms ${LANG_UKRAINIAN} "Я прочитав(-ла) та приймаю умови використання SIDEY."
LangString MaintenanceTitle ${LANG_UKRAINIAN} "SIDEY уже встановлено"
LangString MaintenanceSubtitle ${LANG_UKRAINIAN} "Виберіть потрібну дію."
LangString MaintenanceDescription ${LANG_UKRAINIAN} "Цю версію SIDEY уже встановлено. Ви можете відновити або видалити застосунок."
LangString RepairAction ${LANG_UKRAINIAN} "Відновити"
LangString RemoveAction ${LANG_UKRAINIAN} "Видалити"
LangString CloseAction ${LANG_UKRAINIAN} "Закрити"
LangString DowngradeBlocked ${LANG_UKRAINIAN} "Уже встановлено новішу версію SIDEY, тому інсталятор нічого не змінив. Щоб установити ${APP_VERSION}, видаліть поточну версію SIDEY у Параметри Windows > Програми, а потім знову запустіть цей інсталятор."
LangString LegacyMigrationManual ${LANG_UKRAINIAN} "Установлено попередню MSI-версію SIDEY, тому інсталятор нічого не змінив. Видаліть її в Параметри Windows > Програми, а потім знову запустіть цей інсталятор. Не видаляйте файли встановлення SIDEY вручну."
LangString ExistingRemovalFailed ${LANG_UKRAINIAN} "Не вдалося видалити наявну інсталяцію SIDEY. Потрібні файли можуть бути відсутні або використовуватися.$\r$\n$\r$\nЗнову запустіть цей інсталятор і виконайте відновлення, а потім виберіть видалення. Якщо відновлення завершиться помилкою, перезапустіть Windows і повторіть спробу.$\r$\n$\r$\nНе видаляйте файли встановлення SIDEY вручну."
LangString CleanupTitle ${LANG_UKRAINIAN} "Видалення даних користувача SIDEY"
LangString CleanupSubtitle ${LANG_UKRAINIAN} "Виберіть дані поточного користувача для видалення."
LangString CleanupDescription ${LANG_UKRAINIAN} "Застосунок SIDEY буде видалено. Наведені нижче дані збережуться, якщо не позначити їх для видалення."
LangString DeleteLocalData ${LANG_UKRAINIAN} "Видалити налаштування та журнали (%LOCALAPPDATA%\SIDEY)"
LangString DeleteCredentials ${LANG_UKRAINIAN} "Видалити збережені облікові дані для входу в SIDEY"
LangString CleanupFailed ${LANG_UKRAINIAN} "Застосунок SIDEY видалено, але частину вибраних даних користувача видалити не вдалося.$\r$\n$\r$\nЕлементи, що залишилися, наведено нижче. Вони не впливають на видалення застосунку SIDEY.$\r$\n$CleanupFailureDetails"
LangString CleanupLocalDataFailure ${LANG_UKRAINIAN} "- Налаштування та журнали (%LOCALAPPDATA%\SIDEY)"
LangString CleanupCredentialsFailure ${LANG_UKRAINIAN} "- Збережені облікові дані для входу в SIDEY"
LangString CleanupStartupFailure ${LANG_UKRAINIAN} "- Запис автозапуску SIDEY"
LangString LaunchFailed ${LANG_UKRAINIAN} "SIDEY установлено, але застосунок не вдалося запустити.$\r$\n$\r$\nПерезапустіть Windows і запустіть SIDEY з меню «Пуск»."
LangString TransactionFailed ${LANG_UKRAINIAN} "Встановлення SIDEY не завершено. Якщо SIDEY уже було встановлено, попереднє встановлення збережено або відновлено.$\r$\n$\r$\nЗнову запустіть інсталятор."
LangString TransactionStateUnknown ${LANG_UKRAINIAN} "Під час встановлення виникла проблема, і остаточний стан SIDEY не вдалося підтвердити.$\r$\n$\r$\nПерезапустіть Windows і запустіть останню версію інсталятора SIDEY. Якщо запропоновано відновлення, завершіть його.$\r$\n$\r$\nНе видаляйте файли встановлення SIDEY вручну."
LangString TransactionRecoveryFailed ${LANG_UKRAINIAN} "Не вдалося відновити перерване встановлення SIDEY і підтвердити його остаточний стан.$\r$\n$\r$\nПерезапустіть Windows і знову запустіть останню версію інсталятора SIDEY.$\r$\n$\r$\nНе видаляйте файли встановлення SIDEY вручну."
LangString UninstallPreflightFailed ${LANG_UKRAINIAN} "Не вдалося розпочати видалення SIDEY. Зміни видалення не застосовувалися.$\r$\n$\r$\nЗакрийте SIDEY, перезапустіть Windows і повторіть спробу."
LangString UninstallStateUnknown ${LANG_UKRAINIAN} "Під час видалення виникла проблема, і остаточний стан видалення SIDEY не вдалося підтвердити.$\r$\n$\r$\nПерезапустіть Windows і повторіть видалення за допомогою останньої версії інсталятора SIDEY.$\r$\n$\r$\nНе видаляйте файли встановлення SIDEY вручну."
LangString SetupAlreadyRunning ${LANG_UKRAINIAN} "Інший інсталятор або засіб видалення SIDEY уже запущено.$\r$\n$\r$\nЗакрийте його й повторіть спробу.$\r$\n$\r$\nКод помилки SIDEY: 0x51DE2007"
LangString SetupInitializationFailed ${LANG_UKRAINIAN} "Не вдалося ініціалізувати блокування встановлення SIDEY.$\r$\n$\r$\nПерезапустіть Windows і знову запустіть інсталятор.$\r$\n$\r$\nКод помилки SIDEY: 0x51DE2008"
LangString CleanupPending ${LANG_UKRAINIAN} "SIDEY установлено, але резервну копію попередньої версії видалити не вдалося.$\r$\n$\r$\nЖодних дій не потрібно. Очищення буде повторено під час наступного запуску інсталятора."
LangString PayloadStageFailed ${LANG_UKRAINIAN} "Не вдалося підготувати файли застосунку SIDEY. Наявну інсталяцію не замінено.$\r$\n$\r$\nЗвільніть місце на системному диску Windows і диску встановлення SIDEY, а потім знову запустіть інсталятор."
LangString ProcessStopFailed ${LANG_UKRAINIAN} "Не вдалося оновити файли застосунку, оскільки процес SIDEY усе ще запущено. Наявну інсталяцію збережено.$\r$\n$\r$\nЗакрийте SIDEY і знову запустіть інсталятор. Якщо SIDEY не видно, перезапустіть Windows."
LangString PayloadActivationFailed ${LANG_UKRAINIAN} "Не вдалося застосувати підготовлені файли застосунку SIDEY. Попередню інсталяцію збережено або відновлено.$\r$\n$\r$\nПерезапустіть Windows і знову запустіть інсталятор."
LangString RegistrationFailed ${LANG_UKRAINIAN} "Не вдалося оновити ярлики SIDEY або реєстрацію у Windows. Попередню інсталяцію збережено або відновлено.$\r$\n$\r$\nПерезапустіть Windows і знову запустіть інсталятор."
